### ISSUE TITLE
DetailsProfileComponent

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-nous#36]
- Supprimer `public listEstablishment;` utiliser a la place `public establishments: [];` et typé la correctement.
- Supprimer `public listMessage;` utiliser a la place `public messages: [];` et typé la correctement.
- `NgOnInit` paramètre `etam` comme le magasin ?

**Comment by Gordian05** [comment]
typage et optimisation de DetailsProfileComponent
