### ISSUE TITLE
ListEstablishmentComponent

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-nous#38]
- Supprimer `public listEstablishment;`
- Renommer `listEstablishment` en `establishments` et typé correctement 
- Supprimer `public categorie = this.service.result;` et récupérer la catégorie a partir de la route (voir issue #32, #34 )
- Supprimer la méthode `etaDetail` non utilisé
- Factoriser les deux `<div class=".container">` en un, en utilisant une fonction `.filter` en TS ce qui permet de ne plus avoir besoin de `estaDefault` et `estaCategorie`
- Utiliser `CardComponent` voir issue #50

**Comment by MartialBlot** [comment]
ok
