### ISSUE TITLE
Navigation de "restaurant par categorie" ver "tous les restaurant"

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-nous#49]
Lorsque l'on navigue de la vue "restaurant par categorie" (pizza > show restaurant) on a bien deux restaurants d’affiché mais si on clique sur "all restaurants" rien ne se passe. Sûrement liée
aux issues #38, #32, #34

**Comment by MartialBlot** [comment]
ok fix
